
spring:
  application:
    name: seller-app
  datasource:
    username: market_user
    password: P9uCRdqdXcrEG6c2gQXdsPoVk5Kydcgc
    url: jdbc:postgresql://dpg-ctkk2vggph6c739e39qg-a.oregon-postgres.render.com/market_db_ylv4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    rest:
      base-path: /seller
jwt:
  signatureAlgorithm: HFIDWHFJJfhewbfjk24141535fdg2erhukwebrkq3uqhfbqkbdfkw
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://10.10.3.42:8761/eureka/
springdoc:
  swagger-ui:
    path: /seller/swagger
  api-docs:
    path: /seller/api
