spring:
  application:
    name: gateway
server:
  port: 8080
eureka:
  cloud:
    gateway:
      routes:
        - id: auth-app
          uri: lb//auth-app/
          predicates:
            - Path=/auth/**
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
